### ISSUE TITLE
How to parallelize tasks using web-worker?

### ISSUE THREAD

**Issue by rbhogi** [pgriess/node-webworker#13]
Hi,

I have following simple program. I am looking to parallelize this program using web-worker. 

function process(delay){
    var start = new Date();
    var len = 300000*delay;
    for(var i=0;i<len;i++){};
    return (new Date()-start);
}

var start = new Date();
process(500);
process(600);
console.log("Time taken :"+(new Date()-start));

**Comment by pgriess** [comment]
Not a bug.
