### ISSUE TITLE
Cannot create worker in 0.4.1

### ISSUE THREAD

**Issue by pbcomm** [pgriess/node-webworker#19]
net.js:1016
          throw new Error('Non-socket exists at  ' + path);
                ^
Error: Non-socket exists at  /tmp/node-webworker-88948
    at net.js:1016:17

**Comment by pgriess** [comment]
What exists at that path?

**Comment by pbcomm** [comment]
The folder is there, however it's empty.

**Comment by pgriess** [comment]
The exception is being thrown because the path exists and is not a UNIX domain socket. Did you by chance manually create this directory? I don't see a codepath in node-webworker that would create a directory here.

**Comment by pbcomm** [comment]
I did not create the directory. It's being created when the socket is opened by webworker.
There is a var being set with the same path:

// Directory for our UNIX domain sockets
var SOCK_DIR_PATH = '/tmp/node-webworker-' + process.pid;

**Comment by mhalle** [comment]
I'm seeing the same behavior on Mac OS 10.6.6.

**Comment by czapata** [comment]
I'm seeing this error when creating new workers in node version 0.4.1.

**Comment by kschzt** [comment]
Seems to be because the npm package hasn't been updated? Using master works.

**Comment by pbcomm** [comment]
Confirmed! Master works fine. Please update npm!!!!!
Thanks kschzt.

Tested with 0.4.2 as well, works fine.

**Comment by mirkokiefer** [comment]
Master fixes the problem for me too. Updating npm would be great!
