### ISSUE TITLE
osx support?

### ISSUE THREAD

**Issue by felixge** [pgriess/node-webworker#2]
I'm wondering if OSX is supported at this point?

I can't get your example from the mailing list to work (connections seem to be accepted, but not responded to).

When running the test suite you ship, I can only run test-simple. test-error and test-fd just seem to stall forever.

If you need help with osx I can probably try looking into this.

**Comment by pgriess** [comment]
Yes, OS X should work; I developed this on OS X 10.5.8.

Do you have any ipfw rules that affect port 80? Try this

```
% sudo ipfw show
```

**Comment by felixge** [comment]
```
sudo ipfw show
Password:
00010  1146309  1060009870 divert 8668 ip from any to any via en1
65535 50401347 36713399011 allow ip from any to any
```

I have a web server running on port 80. Are you using port 80 in your tests?

Btw. test-error is actually working, I killed it before the 5 sec timeout. But test-fd is still not running for me.

**Comment by pgriess** [comment]
Are you running the latest bits from ry/node/master? The test-fd test relies on features not in v0.1.97. Running a stale node version would also explain why you're not seeing any HTTP responses in the preforking example.

**Comment by felixge** [comment]
yikes, I did 'git fetch ry', but forgot to update my tree when re-compiling : ). #git #fail

Sorry for the false alarm, seems to work great now!
Thanks
