### ISSUE TITLE
Doesn't work with node 0.6.x - "Error: No such module"

### ISSUE THREAD

**Issue by diversario** [pgriess/node-webworker#35]
Error on `require('webworker')`

``` javascript
Error: No such module
    at Object.<anonymous> (/node_modules/webworker/lib/webworker.js:35:26)
```

Offending line `var netBinding = process.binding('net');` yields same error.

**Comment by francisl** [comment]
Same thing here.

Tried the fix for node-websocket-client. no change

**Comment by francisl** [comment]
I made a patch for it.
You can check my fork https://github.com/francisl/node-webworker
or the push request
https://github.com/pgriess/node-webworker/pull/36

**Comment by 0x80** [comment]
Are you able to pass the tests that come with the lib? For example test-simple?

I can't get any of them to work with node 0.6.7 on osx

**Comment by francisl** [comment]
No, it doesn't works.

**Comment by 0x80** [comment]
Are you successfully using the webworker module anyway? If so, with what version of node?

**Comment by francisl** [comment]
My fix only remove the dependencies error to start the application (0.6.1). But the webworkers does not work.
The problem seems to be deeper in how the threads are handled.

**Comment by vip32** [comment]
also occurs in 0.6.11 not work with node 0.6.7 (No such module)

**Comment by 0x80** [comment]
I get the impression the node webworker library is not actively developed anymore. I found a different way of solving my problem so luckily I don't need it anymore. Abandon ship.

**Comment by vip32** [comment]
I switched to 'cluster', part of the node lib. Works great

**Comment by danielrhodeswarp** [comment]
I also have this problem. I installed with npm. Both require('webworker') and require('../lib/webworker') give the "no such module" error.

**Comment by diversario** [comment]
I don't think it's even needed anymore, I just use child processes and/or cluster.
